-- Autopilot : tendances X, programme TV et journal des posts

alter table public.events
    add column if not exists kind text,
    add column if not exists channel text,
    add column if not exists description text,
    add column if not exists team_a text,
    add column if not exists team_b text,
    add column if not exists source text,
    add column if not exists priority integer,
    add column if not exists updated_at timestamptz not null default now();

create table if not exists public.trends (
    id bigint generated by default as identity primary key,
    fetched_at timestamptz not null default now(),
    rank integer not null,
    title text not null,
    slug text not null,
    volume text
);
create index if not exists trends_fetched_idx on public.trends (fetched_at desc, rank);

create table if not exists public.social_posts (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    network text not null,
    ref text not null,
    slot text not null,
    text text not null,
    status text not null default 'pending',
    external_id text,
    error text,
    unique (network, ref, slot)
);

alter table public.trends enable row level security;
alter table public.social_posts enable row level security;

create policy "trends read" on public.trends for select using (true);
