-- LiveWave : schema public reconstruit depuis le code (backup du 2025-04-10 sans donnees applicatives)
-- A executer dans le SQL Editor d'un nouveau projet Supabase.

create extension if not exists pgcrypto;

create table public.chats (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    title text not null,
    title_full text,
    description text,
    livers integer not null default 0
);
create index chats_title_idx on public.chats (lower(title));

create table public.messages (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    chat_id uuid not null references public.chats(id) on delete cascade,
    username text,
    content text not null check (char_length(content) <= 500),
    reply uuid references public.messages(id) on delete set null,
    likes integer not null default 0
);
create index messages_chat_id_idx on public.messages (chat_id, created_at);

create table public.events (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    name text not null unique,
    nameformat text,
    hashtags text,
    datestart timestamptz,
    dateend timestamptz,
    image text,
    og text,
    messages jsonb,
    tweets jsonb,
    forcebot integer not null default 0
);

create table public.teams (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    event bigint not null references public.events(id) on delete cascade,
    name text not null,
    color text,
    count integer not null default 0
);

create table public.visitors (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    generated_id uuid,
    infos jsonb,
    chat uuid,
    username text
);

create table public.blog (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    keyurl text unique,
    title text not null,
    excerpt text,
    content text,
    image text,
    meta text,
    date date default current_date
);

-- RLS
alter table public.chats    enable row level security;
alter table public.messages enable row level security;
alter table public.events   enable row level security;
alter table public.teams    enable row level security;
alter table public.visitors enable row level security;
alter table public.blog     enable row level security;

create policy "chats read"     on public.chats    for select using (true);
create policy "chats insert"   on public.chats    for insert with check (true);
create policy "chats update"   on public.chats    for update using (true) with check (true);

create policy "messages read"   on public.messages for select using (true);
create policy "messages insert" on public.messages for insert with check (true);
create policy "messages update" on public.messages for update using (true) with check (true);

create policy "events read"    on public.events   for select using (true);

create policy "teams read"     on public.teams    for select using (true);
create policy "teams update"   on public.teams    for update using (true) with check (true);

create policy "visitors insert" on public.visitors for insert with check (true);

create policy "blog read"      on public.blog     for select using (true);

-- Limite les colonnes modifiables par le client anonyme
revoke update on public.chats, public.messages, public.teams from anon, authenticated;
grant update (livers) on public.chats    to anon, authenticated;
grant update (likes)  on public.messages to anon, authenticated;
grant update (count)  on public.teams    to anon, authenticated;

-- Realtime sur les messages
alter publication supabase_realtime add table public.messages;
